name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This action checks out your repository's code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Install Node.js version 14

    - name: Install dependencies
      run: npm install  # Install project dependencies

    - name: Build
      run: npm run build  # Build your project

    - name: Run tests
      run: npm test  # Run your project's tests

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Make sure the 'build' job is completed before deploying

    steps:
    - name: Deploy to production
      # Add your deployment action here, for example:
      # uses: actions/aws/cli@v2
      # with:
      #   args: s3 sync ./build/ s3://your-bucket-name
